import { TutorialStep } from './tutorial-step';

export const tutorialSteps: TutorialStep[] = [
  {
    id: 'homeexpl',
    type: 'explanation',
    text: 'Das ist der Hauptbildschirm, so sieht es aus wenn Sie ChatGPT starten. Hier haben Sie alle Funktionen direkt verfügbar. Welche das sind wird Ihnen nun Schritt für Schritt gezeigt. Dafür werde ich die jeweils beschriebene Funktion rot einrahmen, wie jetzt den ganzen Bildschirm und kurz erklären.',
    textPosition: '20%',
    imageUrl: 'images/home.jpg',
    zones: [{ x: '0', y: '0', width: '100%', height: '100%' }],
  },
  {
    id: 'textinputexpl',
    type: 'explanation',
    linkedTaskId: 'textinputtask',
    text: 'Das ist das Texteingabefeld. Wenn Sie hier drücken, erscheint die Tastatur und Sie können Ihre Frage eintippen.',
    textPosition: '20%',
    imageUrl: 'images/home.jpg',
    zones: [{ x: '18%', y: '87.5%', width: '43%', height: '6%' }],
  },
  {
    id: 'textinputtask',
    type: 'task',
    linkedExplanationId: 'textinputexpl',
    text: 'Tippen Sie auf das Texteingabefeld',
    successText: 'Sehr gut! Sie haben erfolgreich die Texteingabe geöffnet.',
    textPosition: '20%',
    imageUrl: 'images/home.jpg',
    successImageUrl: 'images/texteingabe.jpg',
    zones: [{ x: '18%', y: '87.5%', width: '43%', height: '6%' }],
  },
  {
    id: 'textinputmenuexpl',
    type: 'explanation',
    text: 'Hier können Sie nun Ihre Frage eintippen. Sobald Sie auf den Button unten rechts drücken, wird Ihre Frage an ChatGPT gesendet und Sie erhalten eine Antwort.',
    textPosition: '20%',
    imageUrl: 'images/texteingabe.jpg',
    zones: [{ x: '85%', y: '87.5%', width: '13%', height: '6.5%' }],
  },
  {
    id: 'voiceinputexpl',
    type: 'explanation',
    linkedTaskId: 'voiceinputtask',
    text: 'Das Mikrofon aktiviert die Spracheingabe. Sie können dann einfach in ihr Gerät sprechen, anstatt tippen zu müssen.',
    textPosition: '20%',
    imageUrl: 'images/home.jpg',
    zones: [{ x: '70%', y: '87.5%', width: '11%', height: '6%' }],
  },
  {
    id: 'voiceinputtask',
    type: 'task',
    linkedExplanationId: 'voiceinputexpl',
    text: 'Tippen Sie auf das Symbol für die Spracheingabe.',
    successText: 'Sehr gut! Sie haben die Spracheingabe erfolgreich aktiviert.',
    textPosition: '20%',
    imageUrl: 'images/home.jpg',
    successImageUrl: 'images/spracheingabe.jpg',
    zones: [{ x: '70%', y: '87.5%', width: '11%', height: '6%' }],
  },
  {
    id: 'voiceinputmenuexpl',
    type: 'explanation',
    text: 'An der Linie unten sehen Sie, dass es funktioniert hat. Nun können sie einfach sagen was Sie ChatGPT fragen wollen. Wenn Sie die Eingabe abbrechen möchten drücken Sie unten links auf das Viereck. Wenn Sie die Eingabe abschicken wollen drücken Sie unten rechts auf den Pfeil.',
    textPosition: '20%',
    imageUrl: 'images/spracheingabe.jpg',
    zones: [{ x: '2%', y: '87.5%', width: '96%', height: '6%' }],
  },
  {
    id: 'audiochatexpl',
    type: 'explanation',
    linkedTaskId: 'audiochattask',
    text: 'Die Stimmlinie aktiviert den Audio-Chat.',
    textPosition: '20%',
    imageUrl: 'images/home.jpg',
    zones: [{ x: '81%', y: '87.5%', width: '11%', height: '6%' }],
  },
  {
    id: 'audiochattask',
    type: 'task',
    linkedExplanationId: 'audiochatexpl',
    text: 'Tippen Sie auf das Symbol für den Audio-Chat.',
    successText: 'Sehr gut! Sie haben den Audio-Chat erfolgreich aktiviert.',
    textPosition: '20%',
    imageUrl: 'images/home.jpg',
    successImageUrl: 'images/audiochat.jpg',
    zones: [{ x: '81%', y: '87.5%', width: '11%', height: '6%' }],
  },
  {
    id: 'audiochatmenuexpl',
    type: 'explanation',
    text: 'Im Audiochat wird konstant alles was Sie sagen an ChatGPT gesendet. Um das Mikrofon stumm zu schalten drücken sie auf das Mikrofon. Um den Audio-Chat zu verlassen, drücken sie unten rechts auf beenden.',
    textPosition: '20%',
    imageUrl: 'images/audiochat.jpg',
    zones: [{ x: '58%', y: '87.5%', width: '40%', height: '6.5%' }],
  },
  {
    id: 'plusmenuexpl',
    type: 'explanation',
    linkedTaskId: 'plusmenutask',
    text: 'Das Plus aktiviert das Plus-Menü.',
    textPosition: '20%',
    imageUrl: 'images/home.jpg',
    zones: [{ x: '8%', y: '87.5%', width: '12%', height: '6%' }],
  },
  {
    id: 'plusmenutask',
    type: 'task',
    linkedExplanationId: 'plusmenuexpl',
    text: 'Tippen Sie auf das Feld für das Plus-Menü.',
    successText: 'Sehr gut! Sie haben das Plus-Menü erfolgreich geöffnet.',
    textPosition: '20%',
    imageUrl: 'images/home.jpg',
    successImageUrl: 'images/plusmenu.jpg',
    zones: [{ x: '8%', y: '87.5%', width: '12%', height: '6%' }],
  },
  {
    id: 'plusmenumenuexpl',
    type: 'explanation',
    text: 'Im Plus-Menü haben Sie nun drei Möglichkeiten etwas an ChatGPT zu senden. Links können sie mit ihrer Kamera direkt ein Bild aufnehmen, zum Beispiel von einer Blume. In der Mitte können Sie ein Bild aus ihrer Galerie auswählen und rechts Dateien von ihrem Handy.',
    textPosition: '13%',
    imageUrl: 'images/plusmenu.jpg',
    zones: [{ x: '5%', y: '52%', width: '90%', height: '10%' }],
  },
  {
    id: 'vorherigechatsexpl',
    type: 'explanation',
    linkedTaskId: 'vorherigechatstask',
    text: 'Die zwei Striche oben links, aktivieren das Menü mit den vorherigen Chats.',
    textPosition: '20%',
    imageUrl: 'images/home.jpg',
    zones: [{ x: '2%', y: '4.25%', width: '13%', height: '6%' }],
  },
  {
    id: 'vorherigechatstask',
    type: 'task',
    linkedExplanationId: 'vorherigechatsexpl',
    text: 'Tippen Sie auf das Feld für das Menü mit vorherigen Chats.',
    successText: 'Sehr gut! Sie haben das Menü mit den vorherigen Chats erfolgreich geöffnet.',
    textPosition: '20%',
    imageUrl: 'images/home.jpg',
    successImageUrl: 'images/vorherigechats.jpg',
    zones: [{ x: '2%', y: '4.25%', width: '13%', height: '6%' }],
  },
  {
    id: 'vorherigechatsmenuexpl',
    type: 'explanation',
    text: 'In diesem Menü sehen Sie ihre vorherigen Chats mit ChatGPT und können diese auch wieder aufnehmen, wenn Sie möchten. Unten rechts gibt es noch die Möglichkeit einen neuen Chat anzufangen. Dies empfiehlt sich meistens wenn Sie mit einem neuen Thema beginnen möchten. So fällt auch das nachsehen in alten Chats leichter.',
    textPosition: '10%',
    imageUrl: 'images/vorherigechats.jpg',
    zones: [{ x: '2%', y: '46%', width: '63%', height: '44%' }, { x: '67.65%', y: '84.9%', width: '28%', height: '8%' }],
  },
  {
    id: 'einleitungabfrage',
    type: 'explanation',
    text: 'Sie haben nun jede der Hauptfunktionen einmal gesehen. Schauen wir mal wie viele Sie noch behalten haben. Keine Sorge, Sie können jederzeit noch einmal zurück zu der jeweiligen Lektion gehen um nachzusehen.',
    textPosition: '20%',
    imageUrl: 'images/home.jpg',
  },
];
